config:
  target: "http://localhost:3004"
  phases:
    - duration: 60
      arrivalRate: 500
  payload:
    path: "listingIds.csv"
    fields:
      - "ids"
scenarios:
  - name: "Reach the Stratosphere"
    flow:
      - loop:
        - get:
            url: "/api/listings/{{ ids }}/reviews"
        count: 60
